name: build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Luacheck for linting
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.1"

      - name: Run Luacheck for linting
        uses: RagedUnicorn/action-luacheck@v1.0.0

  test:
    name: "Unit Test"
    needs: lint

    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.luaVersion }}
                   
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0
      
      - name: Install this module
        run: |
          luarocks make

      - name: Install dependencies
        run: |
          luarocks install busted
          luarocks install luacov

      - name: Run Unity Test
        run: |
          busted -o utfTerminal

  coverage:
    name: Coverage
    needs: test

    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.1"
                   
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0
      
      - name: Install this module
        run: |
          luarocks make

      - name: Install dependencies
        run: |
          luarocks install busted
          luarocks install luacov
          luarocks install luacov-reporter-lcov
          
      - name: Test
        run: |
          busted -o utfTerminal --coverage
          luacov -r lcov
        
      - name: Report to Coveralls
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: luacov.report.out
        
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    
      - name: Build base image
        run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}