name: quality-pattern
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lint:
    name: Test
  
    runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Run Luacheck for linting
        uses: RagedUnicorn/action-luacheck@v1.0.0

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0

  test:
    name: Test
    needs: lint

    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.luaVersion }}
                   
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0
      
      - name: Install this module
        run: |
          luarocks make

      - name: Install dependencies
        run: |
          luarocks install busted

      - name: Run Unity Test
        run: |
          busted -o utfTerminal

  coverage:
    name: Coverage
    needs: test

    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.1"
                   
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0
      
      - name: Install this module
        run: |
          luarocks make

      - name: Install dependencies
        run: |
          luarocks install busted
          luarocks install luacov
          luarocks install luacov-coveralls
      
      - name: Run Unity Test
        run: |
          busted --coverage -o utfTerminal

      - name: Generate cobertura
        run: |
          luacov

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token:  ${{ secrets.GITHUB_TOKEN }} 
          # Path to lcov file
          path-to-lcov: luacov.stats.out # default is ./coverage/lcov.info
          # Job flag name, e.g. "Unit", "Functional", or "Integration". Will be shown in the Coveralls UI.
          #flag-name: # optional
          # Set to true if you are running parallel jobs, then use "parallel_finished: true" for the last action.
          #parallel: # optional
          # Set to true for the last action when using "parallel: true".
          #parallel-finished: # optional
          # Coveralls Enterprise server (more info: https://enterprise.coveralls.io)
          #coveralls-endpoint: # optional, default is https://coveralls.io
          # The root folder of the project that originally ran the tests
          #base-path: # optional
          # Override the branch name
          #git-branch: # optional
          # Override the commit sha
          #git-commit: # optional