name: quality-pattern

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout codebases
        uses: actions/checkout@v2

      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: 5.1
                   
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0
      
      - name: Run Luacheck
        uses: RagedUnicorn/action-luacheck@v1.0.0
      
      - name: Setup 
        run: |
          luarocks install busted
          luarocks make
          
      - name: Test
        run: |
          busted -o utfTerminal --coverage
      
      
        
      
        
     

      
